import React from 'react';

import Head from 'next/head';

import { Box, Main } from './styles';

import { ReturnComponentType } from 'types';

export interface LayoutProps {
  className?: string;
  children: React.ReactNode;
}

const Layout = ({ className, children }: LayoutProps): ReturnComponentType => {
  return (
    <Box className={className}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>{children}</Main>
    </Box>
  );
};

export default Layout;
