'use client';

import '../../public/styles/globals.css';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport" />
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </head>
      <body id="__next">{children}</body>
    </html>
  );
}
